# Generated by Django 5.0.6 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="job_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
