# Generated by Django 5.0.6 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="parsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="parsed_content_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
