# Generated by Django 5.0.6 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_interval",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
