# Generated by Django 5.0.6 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_billing_stripe_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
