# Generated by Django 5.0.6 on 2026-05-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0004_subscriptionplan_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("display_name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("qr_payload_template", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("qr_payload_override", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="billing.cryptonetwork",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanCryptoAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("network", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="plan_availability", to="billing.cryptonetwork")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crypto_availability", to="billing.subscriptionplan")),
            ],
            options={
                "unique_together": {("plan", "network")},
            },
        ),
        migrations.CreateModel(
            name="CryptoPaymentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expected_amount", models.DecimalField(decimal_places=8, max_digits=12)),
                ("expected_currency", models.CharField(max_length=20)),
                ("transaction_hash", models.CharField(blank=True, max_length=255)),
                ("sender_address", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("pending_submission", "Pending Submission"), ("pending_review", "Pending Review"), ("approved", "Approved"), ("rejected", "Rejected"), ("expired", "Expired")], default="pending_submission", max_length=30)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("network", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_requests", to="billing.cryptonetwork")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="crypto_requests", to="billing.payment")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="crypto_payment_requests", to="billing.subscriptionplan")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_crypto_payment_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crypto_payment_requests", to=settings.AUTH_USER_MODEL)),
                ("wallet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_requests", to="billing.cryptowallet")),
            ],
        ),
        migrations.CreateModel(
            name="CryptoPaymentReviewLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("submitted", "Submitted"), ("approved", "Approved"), ("rejected", "Rejected"), ("reopened", "Reopened")], max_length=30)),
                ("note", models.TextField(blank=True)),
                ("before_payload", models.JSONField(blank=True, default=dict)),
                ("after_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crypto_payment_review_logs", to=settings.AUTH_USER_MODEL)),
                ("payment_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_logs", to="billing.cryptopaymentrequest")),
            ],
        ),
    ]
