# Generated by Django 5.0.6 on 2026-05-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0005_crypto_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptonetwork",
            name="network_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="cryptonetwork",
            name="token_symbol",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="cryptopaymentrequest",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cryptopaymentrequest",
            name="instruction_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cryptopaymentrequest",
            name="network_name",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptopaymentrequest",
            name="receiver_address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptopaymentrequest",
            name="reference_code",
            field=models.CharField(db_index=True, default="", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptopaymentrequest",
            name="token_symbol",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="network_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_reference",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="token_symbol",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verified_payments", to=settings.AUTH_USER_MODEL),
        ),
    ]
